// src/components/Step.vue
<template>
  <div class="step grid grid-cols-[130px_20px_100px] xl:grid-cols-[200px_50px_100px] gap-1">
    <p class="text-xs xl:text-sm">{{ stepDate }}</p>
    <div class="relative flex justify-center h-3 w-3 xl:h-5 xl:w-5">
      <div class="absolute h-16 border-2 border-blue-300"></div>
      <div class="absolute inline-flex h-full w-full rounded-full bg-blue-300 opacity-100"></div>
      <div class="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-300 opacity-100"></div>
    </div>
    <p class="text-xs xl:text-base font-bold">{{ stepTitle }}</p>
  </div>
</template>
<script>
export default {
  name: 'Step',
  props: ["stepDate","stepTitle"]
}
</script>
<style>
.step {
  display: grid;
}
</style>

// src/Components/Step/Step.jsx
import "./Step.css";
import PropTypes from "prop-types";

const Step = ({stepData}) => {
    const width = "mobile:w-4 tablet:w-5 laptop:w-6"
    const height = "mobile:h-4 tablet:h-5 laptop:h-6"
    return (
        <div className="step">
            <span className={"relative flex my-10 " + `${width} ${height}`}>
              <span
                  className="animate-ping absolute inline-flex h-full w-full rounded-full bg-sky-400 opacity-75"></span>
              <span className={"relative inline-flex rounded-full bg-sky-500 " + `${width} ${height}`}></span>
            </span>
            <div className="mx-3 rounded-lg hover:shadow-md hover:shadow-sky-300 p-3">
                <p className="text-nowrap font-thin mobile:text-base">{stepData.stepDate}</p>
                <p className="text-sky-400 font-medium mobile:text-xl">{stepData.stepTitle}</p>
                <p className="text-sky-400 font-light mobile:text-xl">{stepData.stepPosition}</p>
            </div>
        </div>
    );
}

Step.propTypes = {
    stepData: PropTypes.object
}

export default Step;
