// src/components/NavBar.vue
<template>
  <div class="mt-10" style="width: 100%">
    <ul class="nav-bar">
      <li v-for="tab in tabs" :class="'nav-bar-tab text-center h-30 sm:h-20 md:text-sm sm:text-xs' + (tab === currTab ? ' active': '')"
           @click="changeTab(tab)">
        {{ tab }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: "NavBar",
  data() {
    return {
      currTab: "Work Experience",
      tabs: ["Work Experience", "Projects", "Education & Courses"]
    }
  },
  methods: {
    changeTab(tabName) {
      this.currTab = tabName;
    }
  }
}
</script>


<style scoped>
.nav-bar {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: space-around;
}

.nav-bar-tab {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.nav-bar-tab.active, .nav-bar-tab.active:hover{
  --tw-text-opacity: 1;
  color: rgb(254 243 199 / var(--tw-text-opacity));
  border-bottom: 4px solid rgb(254 243 199 / var(--tw-text-opacity));
  font-weight: bold;
  transition: ease 0.5s;
}

.nav-bar-tab:hover {
  --tw-text-opacity: 1;
  color: rgb(147 197 253 / var(--tw-text-opacity));
}

</style>

// src/Components/NavBar/NavBar.jsx
import "./NavBar.css";
import {useState} from "react";

const NavBar = () => {
    const tabs = ["Work Experience", "Projects", "Education & Courses"]
    const [currTab, setCurrTab] = useState("Work Experience")
    return (
        <div className="mt-5 flex justify-center">
            <ul className="nav-bar w-[100%] xl:w-[70%]">
                {
                    tabs.map((tab) =>
                        <li
                            className={"nav-bar-tab text-center h-8 md:h-10 xl:h-12 text-xs md:text-base xl:text-lg " + (tab === currTab ? 'active' : '')}
                            onClick={() => setCurrTab(tab)} key={tab}>
                            {tab}
                        </li>
                    )
                }
            </ul>
        </div>
    );
}

export default NavBar;
