// src/components/TimeLine.vue
<template>
  <div class="timeline">
    <div class="mt-2 relative">
      <Step v-for="(step, index) in steps" :step-date="step.stepDate" :step-title="step.stepTitle"
            :step-description="step.description" :line-length="index !== steps.length - 1 ? 'h-full':'h-0'"/>
    </div>
  </div>

</template>
<script>
import Step from "./Step.vue";

export default {
  name: "TimeLine",
  components: {Step},
  props: ["steps"]
}
</script>
<style scoped>
.timeline {
  width: 100%
}

</style>

// src/Components/Timeline/Timeline.jsx
import Step from "@/Components/Step/Step.jsx";
import WorkExperience from "@/assets/Work-Experience.json";

const Timeline = () => {
    const workExperience = WorkExperience;
    return (
        <div className="timeline">
            <div className="line border-sky-400 border-2 w-0 h-full">
                <div className="py-2 relative">
                    {workExperience.map((item, index) => <Step stepData={item} key={index}/>)}
                </div>
            </div>
        </div>
    );
}
export default Timeline;
